export enum ActionEnum {
  SET_CREDIT_AMOUNT = 'SET_CREDIT_AMOUNT',
  SET_CREDIT_TERM = 'SET_CREDIT_TERM',
  SET_INITIAL_FEE = 'SET_INITIAL_FEE',
  SET_INITIAL_FEE_PERCENT = 'SET_INITIAL_FEE_PERCENT',
  SET_PAYMENT_TYPE = 'SET_PAYMENT_TYPE',
  SET_PRICE = 'SET_PRICE',
  SET_RATE = 'SET_RATE',
  SET_TERM_TYPE = 'SET_TERM_TYPE',
  SET_TYPE = 'SET_TYPE',
}
